#!/bin/bash
PLACE=".1.3.6.1.4.1.53864.1.1"  # Requested OID

#
#  Process SET requests by simply logging the assigned value
#      Note that such "assignments" are not persistent,
#      nor is the syntax or requested value validated
#  
echo "Version: 6.1.1"
